CREATE OR REPLACE PROCEDURE FETCH_POS_BY_DATE_CREATED (
    P_DATE_CREATED IN PURCHASE_ORDER.DATE_CREATED%TYPE,
    P_RESULT OUT SYS_REFCURSOR
)
AS
BEGIN
    OPEN P_RESULT FOR 
        SELECT * 
        FROM PURCHASE_ORDER 
        WHERE DATE_CREATED <= P_DATE_CREATED;
END;