CREATE OR REPLACE PROCEDURE FETCH_POLIS_BY_ORDER_ID (
    P_ORDER_ID IN PURCHASE_ORDER_LINE_ITEM.ORDER_ID%TYPE,
    P_RESULT OUT SYS_REFCURSOR
)
AS
BEGIN
    OPEN P_RESULT FOR 
        SELECT * 
        FROM PURCHASE_ORDER_LINE_ITEM 
        WHERE ORDER_ID = P_ORDER_ID;
END;