CREATE TABLE PURCHASE_ORDER (
    ID VARCHAR2(40) PRIMARY KEY,
    REQUESTED_BY VARCHAR2(75) NOT NULL,
    ORDERED_BY VARCHAR2(75) NOT NULL,
    BRANCH VARCHAR2(5) NOT NULL,
    SUPPLIER VARCHAR2(50) NOT NULL,
    REMARKS VARCHAR2(1000),
    DATE_CREATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    STATUS VARCHAR2(12) NOT NULL
);

CREATE TABLE PURCHASE_ORDER_LINE_ITEM (
    ORDER_ID VARCHAR2(40),
    ID VARCHAR2(40),
    ITEM_CODE VARCHAR2(10) NOT NULL,
    ITEM_DESCRIPTION VARCHAR2(250),
    QUANTITY INTEGER NOT NULL,
    UNIT_PRICE DECIMAL NOT NULL,
    UNIT_OF_MEASURE VARCHAR2(3) NOT NULL,
    CONSTRAINT PK_PURCHASE_ORDER_LINE_ITEM PRIMARY KEY(ORDER_ID, ID)
)